### ISSUE TITLE
uber.check_login API Call

### ISSUE THREAD

**Issue by meporter** [jasonkeene/python-ubersmith#41]
Does this command work? If so, can you provide an example?

I am receiving

ubersmith.exceptions.ResponseError: An error occured in the response from the Ubersmith API. 1 missing login or pass parameters

Thanks in advance.

**Comment by theY4Kman** [comment]
A cached version of Ubersmith's API documentation can be found in docs/ubersmith_api_docs.pdf. However, those docs may not match your version of Ubersmith. You can use the `uber.documentation()` method to get the appropriate docs for your own version.

The parameters in the docs translate into Python kwargs. However, I'm not sure if there is any machinery to handle `pass` (i.e. `uber.check_login(login='...', pass='')` would be invalid Python)... so an example usage, using dict unpacking, might be:

```python
import ubersmith  # or import ubersmith.uber if v0.3.9 or lower
user_data = ubersmith.uber.check_login(**{'login': 'username', 'pass': 'password'})
```

Let me know if you have further questions! :)

**Comment by meporter** [comment]
Still fails. Due to cleaner

```
>>> import ubersmith.uber
>>> uber.check_login(**{'login': 'username', 'pass': 'password'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ubersmith/calls/__init__.py", line 114, in __call__
    return self.call_class(kwargs, self.request_handler).render()
  File "/usr/local/lib/python2.7/site-packages/ubersmith/calls/__init__.py", line 49, in render
    self.process_request()
  File "/usr/local/lib/python2.7/site-packages/ubersmith/calls/__init__.py", line 67, in process_request
    self.method, self.request_data)
  File "/usr/local/lib/python2.7/site-packages/ubersmith/api.py", line 281, in process_request
    raise ResponseError(response=resp.json)
ubersmith.exceptions.ResponseError: An error occured in the response from the Ubersmith API. 1 missing login or pass parameters
```

**Comment by theY4Kman** [comment]
Oh, that's interesting. When you see a `ResponseError`, it means the API call did reach Ubersmith, so in this case, the exception wasn't thrown by the cleaner. Now, since we presumably sent the right parameters, and yet Ubersmith thinks we didn't, my first hypotheses for troubleshooting would be to check if the parameters are actually being handed off to the `requests` library.

Are you familiar with [pdb](https://pymotw.com/2/pdb/)? If not, tell me and I can help out. Regardless, here's what I would do:

1. Set a breakpoint right before `requests.post()` in the request handler. This would be in [ubersmith/api.py on line 292](https://github.com/jasonkeene/python-ubersmith/blob/master/ubersmith/api.py#L292).
2. Execute the example `uber.check_login` call
3. Print out the `data` dict variable
4. Ensure it has both the `'login'` and `'pass'` keys

**Comment by meporter** [comment]
I'll run it through pdb shortly. In the interim, I have learned that everything works correctly when passing as you noted

` user_data = ubersmith.uber.check_login(**{'login': 'username', 'pass': 'password'})`

Where I am getting the aforementioned error is when running via `python -i bin/console.py`.

**Comment by theY4Kman** [comment]
Hmm, I can't imagine why it would only fail when run through that. Regardless, using console.py isn't necessary; you can do the `from ubersmith import *` yourself in a regular Python console, if you run it from the parent folder of ubersmith/, or you do `python setup.py install` or similar.

As you got `uber.check_login` to run, I'll consider this resolved, but lemme know if you have further issues.
